# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'UniversityPredictor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Analytics'
pod 'Firebase/Database'
end
